version: '3.4'
services:
  ############################
  # node app + Dapr sidecar
  ############################
  nodeapp:
    build: ./website
    depends_on:
      - redis
      - placement
    ports:
      - "3333:3000"
    networks:
      - show-time     
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "nodeapp",
    "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp"
  ############################
  # python service1
  ############################
  pythonapp1:
    build: ./python_service1
    depends_on:
      - redis
      - placement
    ports:
      - "50003:50002"      
    networks:
      - show-time     
  pythonapp1-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "pythonapp1",
    "-app-port", "5500",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50003",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - pythonapp1
    network_mode: "service:pythonapp1"
  ############################
  # Python service2
  ############################
  pythonapp2:
    build: ./python_service2
    depends_on:
      - redis
      - placement
    ports:
      - "50004:50002"      
    networks:
      - show-time
  pythonapp2-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "pythonapp2",
    "-app-port", "5500",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50004",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - pythonapp2
    network_mode: "service:pythonapp2"    
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - show-time
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - show-time
networks:
    show-time: