version: '3.4'
services:
   
  ############################
  # Api Gateway Service
  ############################
  api-gateway-service:
      build: ./api-service/api-gateway-service
      ports:
        - "5202:80"
      networks:
        - open-data                    
  ############################
  # MongoDB
  ############################
  mongo:
    restart: always
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - auth-db-data:/data/db
    networks:
            - open-data        
  ############################
  # identity server資料庫
  ############################             
  identity-server-db:
    restart: always
    build: ./db/identity-server-db  
    user: root
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
        - identity-server-db-data:/var/opt/mssql      
    ports:
      - 8734:1433
    networks:
      - open-data                                                    
networks:
    open-data:
volumes:
    auth-db-data:
    identity-server-db-data: