version: '3.4'
services:
  ############################
  # node app + Dapr sidecar
  ############################
  nodeapp:
    build: ./website
    depends_on:
      - redis
      - placement
    ports:
      - "3333:3000"
    networks:
      - open-data     
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "nodeapp",
    "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp"
  ############################
  # kao service
  ############################
  kao-service:
    build: ./api-service/kao-service
    depends_on:
      - redis
      - placement
    ports:
      - "50003:50002"
      - "8100:8000"     
    networks:
      - open-data     
  kao-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "kao-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50003",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - kao-service
    network_mode: "service:kao-service" 
  ############################
  # Tainan Service
  ############################
  tainan-service:
    build: ./api-service/tainan-service
    depends_on:
      - redis
      - placement
    ports:
      - "50007:50002"  
      - "8200:8000"       
    networks:
      - open-data
  tainan-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "tainan-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50007",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - tainan-service
    network_mode: "service:tainan-service"  
############################
  # Auth Service
  ############################
  auth-service:
    build: ./api-service/auth-service
    depends_on:
      - redis
      - placement
    ports:
      - "50008:50002"  
      - "8300:8000"       
    networks:
      - open-data
  auth-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "auth-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50008",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - auth-service
    network_mode: "service:auth-service"        
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - open-data   
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - open-data
networks:
    open-data: