version: '3.4'
services:
  ############################
  # node app + Dapr sidecar
  ############################
  # nodeapp:
  #   build: ./website
  #   depends_on:
  #     - redis
  #     - placement
  #   ports:
  #     - "3333:3000"
  #   networks:
  #     - open-data     
  # nodeapp-dapr:
  #   image: "daprio/daprd:edge"
  #   command: ["./daprd",
  #   "-app-id", "nodeapp",
  #   "-placement-host-address", "placement:50006",
  #    "-components-path", "/components"]
  #   volumes:
  #     - "./components/:/components"
  #   depends_on:
  #     - nodeapp
  #   network_mode: "service:nodeapp"
  ############################
  # kao service
  ############################
  kao-service:
    build: ./kao_service
    depends_on:
      - redis
      - placement
    ports:
      - "50003:50002"
      - "8100:8000"     
    networks:
      - open-data     
  kao-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "kao-service",
    "-app-port", "5500",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50003",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - kao-service
    network_mode: "service:kao-service"
  ############################
  # Python service2
  ############################
  # pythonapp2:
  #   build: ./python_service2
  #   depends_on:
  #     - redis
  #     - placement
  #   ports:
  #     - "50004:50002"      
  #   networks:
  #     - open-data
  # pythonapp2-dapr:
  #   image: "daprio/daprd:edge"
  #   command: ["./daprd",
  #   "-app-id", "pythonapp2",
  #   "-app-port", "5500",
  #   "-placement-host-address", "placement:50006",
  #   "-dapr-grpc-port", "50004",
  #    "-components-path", "/components"]
  #   volumes:
  #     - "./components/:/components"
  #   depends_on:
  #     - pythonapp2
  #   network_mode: "service:pythonapp2"    
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - open-data
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - open-data
networks:
    open-data: