version: '3.4'
services:
  ############################
  # Website Service
  ############################
  nodeapp:
    build: ./website
    depends_on:
      - redis
      - placement
    ports:
      - "3333:3000"
    networks:
      - open-data     
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "nodeapp",
    "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp"
  ############################
  # Kao Api Service
  ############################
  kao-service:
    build: ./api-service/kao-service
    depends_on:
      - redis
      - placement
    ports:
      - "50003:50002"
      - "8100:8000"     
    networks:
      - open-data     
  kao-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "kao-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50003",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - kao-service
    network_mode: "service:kao-service" 
  ############################
  # Tainan Api Service
  ############################
  tainan-service:
    build: ./api-service/tainan-service
    depends_on:
      - redis
      - placement
    ports:
      - "50007:50002"  
      - "8200:8000"       
    networks:
      - open-data
  tainan-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "tainan-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50007",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - tainan-service
    network_mode: "service:tainan-service"  
  ############################
  # PTHG Api Service
  ############################
  pthg-service:
    build: ./api-service/pthg-service
    depends_on:
      - redis
      - placement
    ports:
      - "50009:50002"  
      - "8400:8000"       
    networks:
      - open-data
  pthg-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "pthg-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50009",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - pthg-service
    network_mode: "service:pthg-service"  
 ############################
  # Taichung Api Service
  ############################
  taichung-service:
    build: ./api-service/taichung-service
    depends_on:
      - redis
      - placement
    ports:
      - "50010:50002"  
      - "8600:8000"       
    networks:
      - open-data
  taichung-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "taichung-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50010",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - taichung-service
    network_mode: "service:taichung-service"      
  ############################
  # Auth Api Service
  ############################
  auth-service:
    build: ./api-service/auth-service
    depends_on:
      - redis
      - placement
      - mongo
    ports:
      - "50008:50002"  
      - "8300:8000"       
    networks:
      - open-data
    environment:
        ENVIRONMENT: production
  auth-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "auth-service",
    "-app-port", "8000",
    "-placement-host-address", "placement:50006",
    "-dapr-grpc-port", "50008",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - auth-service
    network_mode: "service:auth-service"        
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - open-data   
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - open-data
  ############################
  # MongoDB
  ############################
  mongo:
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - auth-db-data:/data/db
    networks:
            - open-data        
  ############################
  # MongoDB網頁版管理系統
  ############################  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 5469:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
            - mongo   
    networks:
            - open-data                       
networks:
    open-data:
volumes:
    auth-db-data:      