apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "account-service"
        dapr.io/app-port: "8781"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: account-service
        image: localhost:5000/account-service:latest
        env:
          # - name: CLIENT
          #   valueFrom:
          #     secretKeyRef:
          #       name: opendatasecrets
          #       key: client
          # - name: SCOPE
          #   valueFrom:
          #     secretKeyRef:
          #       name: opendatasecrets
          #       key: scope
          # - name: SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: opendatasecrets
          #       key: secret
          # - name: MONGODB
          #   valueFrom:
          #     secretKeyRef:
          #       name: opendatasecrets
          #       key: mongodb                
          - name: ENVIRONMENT
            value: production                              
        ports:
        - containerPort: 8781
        imagePullPolicy: Always
