apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-service
  labels:
    app: personal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-service
  template:
    metadata:
      labels:
        app: personal-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "personal-service"
        dapr.io/app-port: "8782"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"        
    spec:
      containers:
      - name: personal-service
        image: localhost:5000/personal-service:latest
        env:               
          - name: ENVIRONMENT
            value: production                              
        ports:
        - containerPort: 8782
        imagePullPolicy: Always
