apiVersion: apps/v1
kind: Deployment
metadata:
  name: pthg-service
  labels:
    app: pthg-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pthg-service
  template:
    metadata:
      labels:
        app: pthg-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pthg-service"
        dapr.io/app-port: "8780"
    spec:
      containers:
      - name: pthg-service
        image: localhost:5000/pthg-service:latest
        env:
          - name: CLIENT
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: client
          - name: SCOPE
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: scope
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: secret
          - name: ENVIRONMENT
            value: production        
        ports:
        - containerPort: 8780
        imagePullPolicy: Always
