apiVersion: apps/v1
kind: Deployment
metadata:
  name: taichung-service
  labels:
    app: taichung-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taichung-service
  template:
    metadata:
      labels:
        app: taichung-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "taichung-service"
        dapr.io/app-port: "8778"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: taichung-service
        image: localhost:5000/taichung-service:latest
        env:
          - name: CLIENT
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: client
          - name: SCOPE
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: scope
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: opendatasecrets
                key: secret
          - name: ENVIRONMENT
            value: production        
        ports:
        - containerPort: 8778
        imagePullPolicy: Always
