apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service2
  labels:
    app: python-service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service2
  template:
    metadata:
      labels:
        app: python-service2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-port: "5500"
        dapr.io/app-id: "python-service2"
    spec:
      containers:
      - name: python-service2
        image: moon791017/python_service2:v0
